title: Code IT - El evento para desarrolladores de Intermark IT
description: Evento organizado por Intermark IT para desarrolladores
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://code-it.es" # the base hostname & protocol for your site
author: Intermark IT

# Build settings
markdown: kramdown
permalink: pretty
lang: es_ES

include: ['_20XX_pages', '_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

facebook:
  app_id: 

logo: "../css/default_style/img/icon-large.png"

social: 
  name: Intermark IT
  links: 
    - https://twitter.com/intermark_it
    - https://es.linkedin.com/company/grupo-intermark

google_site_verification: J9W0bDDuFUaRLINS4kQHU19Z5JQBsrDdfxJ8F84B7Fo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/intermark_it
  - title: linkedin
    url: https://es.linkedin.com/company/grupo-intermark

